name: harry_potter
description: Layout example

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^3.0.4
  isar_flutter_libs: ^3.0.4
  provider: ^6.0.4
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  isar_generator: ^3.0.4
  build_runner: ^2.3.2

flutter:
  uses-material-design: true